### ISSUE TITLE
Can't connect to a local serial port

### ISSUE THREAD

**Issue by wwahammy** [qca/boardfarm#4]
As a straightforward example of how #2 causes difficulties, it's currently not possible to connect to a local serial port. This is primarily due to the issues in #2.

I see two ways of fixing this:
1. We could simply put the Ser2Net connection code behind an if statement and continue to use the conn_cmd with some sort of serial console program. This is the quickest but isn't all that flexible or user friendly
2. We could implement serial port handling for local serial ports.

I support number 2 as it reduces the work on users and makes boardfarm itself more flexible. That said, it will require a bit of work. This work likely includes:
- modularizing code for connection types, including ser2net
- developing more expandable ways to handle configuration data. (allowing arbitrary configuration data so "connection modules" can grab it)

I've done a prototype of modularizing the code but before going further, I'd like to know what people think about this. Is this worth the trouble? And if so, would anyone else be interested in collaborating on this?

**Comment by bittorf** [comment]
what else makes sense as an connection? e.g. a virtual serial line?

**Comment by wwahammy** [comment]
Depending on use-case, I could see someone choosing to use ethernet. Not really sure offhand.

**Comment by wwahammy** [comment]
@bittorf Another situation is where the serial server is expected to provide a different response than the ser2net response described at https://github.com/qca/boardfarm/blob/master/devices/openwrt_router.py#L57-L63

**Comment by bittorf** [comment]
@ericschultz yes, valid point.
