### ISSUE TITLE
iPerf tests fails

### ISSUE THREAD

**Issue by iniesC** [qca/boardfarm#42]
My iPerfTest fails at parse_iperf() function waiting for the 5th packet that never returns. However, if I run iperf manually I see all 5 packets return. I even tried increasing the client.expect timeout value to t+90. See below for error:

==================== Begin iPerfTest ====================

root@raspberrypi:~# iperf -v
iperf version 2.0.5 (08 Jul 2010) pthreads
root@raspberrypi:~# 
root@raspberrypi:~# iperf -v
iperf version 2.0.5 (08 Jul 2010) pthreads
root@raspberrypi:~# mpstat -V
sysstat version 10.1.7
(C) Sebastien Godard (sysstat <at> orange.fr)
root@OpenWrt:/# killall -9 iperf
iperf: no process found
root@raspberrypi:~# iperf -s  > /dev/null &
[1] 10971
root@raspberrypi:~# mpstat -P ALL 10000 1
## Linux iperf  -c 192.168.0.1 -t 60 -P 5 | grep -v SUM

Client connecting to 192.168.0.1, TCP port 5001
## TCP window size: 1.29 MByte (default)

[  7] local 192.168.1.197 port 34893 connected with 192.168.0.1 port 5001
[  5] local 192.168.1.197 port 34891 connected with 192.168.0.1 port 5001
[  6] local 192.168.1.197 port 34892 connected with 192.168.0.1 port 5001
[  3] local 192.168.1.197 port 34890 connected with 192.168.0.1 port 5001
[  4] local 192.168.1.197 port 34889 connected with 192.168.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-60.1 sec  91.5 MBytes  12.8 Mbits/sec
[  6]  0.0-60.2 sec  92.4 MBytes  12.9 Mbits/sec
[  7]  0.0-60.4 sec  59.8 MBytes  8.30 Mbits/sec
[  5]  0.0-60.4 sec  91.8 MBytes  12.7 Mbits/sec

=========== Test failed! Running recovery ===========
  File "/home/inies/boardfarm/tests/linux_boot.py", line 64, in testWrapper
    self.runTest()
  File "/home/inies/boardfarm/tests/iperf_test.py", line 111, in runTest
    rate = self.parse_iperf(client)
  File "/home/inies/boardfarm/tests/iperf_test.py", line 55, in parse_iperf
    m = client.expect(['Bytes([^M]_)Mbits', 'Bytes([^K]_)Kbits' ], timeout=t+90)

^C^C
root@raspberrypi:~# killall -9 iperf
[1]+  Killed                  iperf -s > /dev/null
root@raspberrypi:~# 
==================== End iPerfTest ======================
<junitxml.JUnitXmlResult run=1 errors=1 failures=0>
Wrote /home/inies/boardfarm/results/test_results.xml
  board_type: ap148
  conn_cmd: cu -l /dev/ttyUSB2 -s 115200
  connection_type: local_serial
  lan_device: 10.75.0.145
  location: mtv
  notes: Reference board
  powerip: 10.75.0.150
  powerport: 4
  station: board01
  wan_device: 10.75.0.146
No elasticsearch_server specified in config. Results stored locally

**Comment by iniesC** [comment]
The quick fix I didis below: I send the client a newline before every expect.

client.sendline("\n")
m = client.expect(['Bytes([^M]_)Mbits', 'Bytes([^K]_)Kbits' ], timeout=t+30)

**Comment by iniesC** [comment]
The above work around or fix doesn't work consistently

**Comment by wwahammy** [comment]
@iniesC Hmmm, this is very strange. I've not noticed this behavior previously. Before your workaround was it consistently failing waiting for the 5th packet?

**Comment by iniesC** [comment]
@ericschultz, yes it is consistently failing via automation but works manually. The pexpect is not seeing the 5th packet everytime.

**Comment by wwahammy** [comment]
@iniesC I'm really not sure what's going on. I've never seen anything like that. I'm sorry.

**Comment by iniesC** [comment]
@ericschultz, sorry for the late delay. It looks like a DUT issue. You are good to close this one.

**Comment by wwahammy** [comment]
No problem, thanks for letting us know!
