### ISSUE TITLE
Discussion location for the project

### ISSUE THREAD

**Issue by wwahammy** [qca/boardfarm#56]
We've had discussions done in a couple different places for the project but we don't seem to have a single place. It'd be ideal to have main place where we can discuss ideas, plans and help new users that isn't the issue tracker. There are a few ways of doing this I can think of. I'd like to get some feedback on this. The choices I can see are:
- No change
- Set up mailing list
- Forum (like discourse)
- IRC
- Slack/Mattermost

Each of them have different advantages. In an ideal world, we'd have multiple ones of these but that requires additional folks. Considering the size of the project, keeping up with one of these is going to be difficult. That said, I really think we should try to decide on something so we can grow the project and bring new folks in.

What does everyone else think?

**Comment by wwahammy** [comment]
I originally decided to do IRC (despite my own dislike for it) but I figured it'd be better to get a sense of what folks are thinking on this.

**Comment by mattsm** [comment]
I'd do IRC... freenode #bft?

**Comment by mbanders** [comment]
I'd prefer mailing list or forum myself.  outside IRC access is generally prohibited at our company.  I've been told that a few times.  (Maybe they could make exceptions?)

**Comment by erikarn** [comment]
It's 2016. We can just use slack :)

A

**Comment by mattsm** [comment]
They can make exceptions, mailing list would be good to have too.

-M

**Comment by wwahammy** [comment]
@erikarn I enjoy Slack but it has the problem that you need to sign up just to "lurk". It just seems a bit discouraging. (It's also non-free but that's not a hard restriction)

I've set up a mailing list for BoardFarm at boardfarm@lists.prplfoundation.org (sign up at http://lists.prplfoundation.org/cgi-bin/mailman/listinfo/boardfarm)

Additionally, I've set up an IRC channel, #boardfarm on Freenode. Feel free to join both!

(I'll also add this info to Readme.MD)
