### ISSUE TITLE
hard coded username "root" to connect to the boards? 

### ISSUE THREAD

**Issue by yi-liang** [qca/boardfarm#65]
Seems when SSH connect to a board, the expected prompt is
prompt = ['root\@._:._#', '/ # ', ".*:~ #",".+@.+:~\$"]
/boardfarm/devices/debian.py line 21
which doesn't handle for generic/customised prompt?
e.g.  raspberry pi's user name could be pi

**Comment by fasolens** [comment]
You can add to the prompt list what you need. To use non root user you need to use sudo before a lot of commands.

**Comment by mattsm** [comment]
Also running as a non-root user has not quite been resolved yet.

**Comment by wwahammy** [comment]
@yi-liang: As @mattsm said, boardfarm doesn't really support running as a non-root user yet. prpl's fork of Boardfarm https://github.com/prplfoundation/boardfarm does have a prototype of non-root user support but it's not in a state where it can be merged upstream. That said, it does function moderately well for us so I encourage you to check out the work we've done.

I'll also be doing a presentation tomorrow at the prplwrt meeting on how prpl sets up boardfarm so I'll try to address some of the changes there.

**Comment by yi-liang** [comment]
thanks, @fasolens  @mattsm @ericschultz
