### ISSUE TITLE
timeout in the nmap tests

### ISSUE THREAD

**Issue by yi-liang** [qca/boardfarm#75]
it seems the timeout for nmap scan report was hard code to 660
 /tests/nmap.py 
`lan.expect('Nmap scan report', timeout=660)`
When we ran the test, this timeout was not enough, so increased it to about 800 then the test can pass

Is there any particular reason to choose 660 as timeout? would it better to make it configurable?
Thanks

**Comment by mbanders** [comment]
If you like, you can submit a code change with the timeout increased to 800 or whatever.

It's really hard to predict how long nmap will take because it depends on a variety of factors.  It can change drastically if you change the number of ports scanned or the methods nmap uses.
