### ISSUE TITLE
assert the number of opened ports is 0 in Nmap_WAN?

### ISSUE THREAD

**Issue by yi-liang** [qca/boardfarm#76]
boardfarm/tests/nmap.py
in test Nmap_WAN, there is 
`assert len(open_ports) == 0`
should it be 
`assert len(open_ports) != 0`
? 
because it would find some open ports then test failed

**Comment by mbanders** [comment]
The test is correct as it is.

The goal of the Nmap_WAN test is to verify there are no open ports on the WAN.  For security, there should be no open ports on the WAN of a consumer router.  So `len(open_ports)` should be equal to 0.  If that happens, the test passes.
