### ISSUE TITLE
Flash via LAN port

### ISSUE THREAD

**Issue by wwahammy** [qca/boardfarm#78]
I'm trying to set up a station to test a EASY92080 DSL router from Intel. The DSL router has a DSL for the  WAN port and four LAN ports. In this case, I'd need to flash the router via the LAN port. This is a problem in Boardfarm as all of the TFTP flashing support assumes that the WAN device will be the TFTP server. In this case, we have no WAN device and we need to flash for the LAN device.

I've been thinking of ways to address them and some of themseem to imply that we'll have to significantly modify how TFTP is setup on devices. For example, we could make TFTP a capability of sorts and allow any device to be setup as a TFTP server. This means pulling some of the code out of [debian.setup_as_wan_gateway](https://github.com/qca/boardfarm/blob/master/devices/debian.py#L132-L22). 

Another way we could do it as allow the LAN configure as a WAN right before the flash happens and then reconfigure back after the flash is complete. I'm unsure on the consequences of this though.

What do folks think?

**Comment by mattsm** [comment]
I've added some code to my master branch to do just this, can you test it out?

mattsm./boardfarm

**Comment by mattsm** [comment]
This code is merged
